name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Eslint:
    strategy:
        matrix:
          os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Lint
        run: npm run eslint
