name: ESLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Eslint:
    strategy:
        matrix:
          os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run Lint
        run: npm run eslint
